---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "git_email"
      prompt: "Email address to set in gitconfig"

  vars_files:
    - vars/main.yml

  roles:
    - { role: geerlingguy.homebrew, when: ansible_os_family == 'Darwin' }
    - { role: macos-setup, when: ansible_os_family == 'Darwin' }
    - { role: credentials, when: ansible_os_family == 'Darwin' }
    - dotfiles

  tasks:
    - name: Install dev-related python packages to python3 installation
      shell: pip3 install ipython flake8 jedi autopep8 ipdb redis requests
