---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "git_email"
      prompt: "Email address to set in gitconfig"

  vars_files:
    - vars/main.yml

  roles:
    # - geerlingguy.homebrew
    - credentials
    - dotfiles

  tasks:
    - name: Install dev-related python packages to python3 installation
      shell: pip3 install ipython flake8 jedi autopep8 ipdb redis requests

    - name: Show Library folder in Finder
      shell: chflags nohidden ~/Library

    - name: Show all filename extensions in Finder
      shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    - name: Save screenshots to Downloads folder
      shell: defaults write com.apple.screencapture location ~/Downloads/
