---
- hosts: localhost
  connection: local

  vars:
    - git_email: "{{ lookup('env','EMAIL') }}"
    - credentials_path: "{{ lookup('env','CREDENTIALS_PATH') }}"

  vars_files:
    - vars/main.yml

  roles:
    #- { role: geerlingguy.homebrew, when: ansible_os_family == 'Darwin' }
    - { role: credentials, when: credentials_path != '' }
    - { role: macos-setup, when: ansible_os_family == 'Darwin' }
    - dotfiles

  tasks:
    - name: Install dev-related python packages to python3 installation
      shell: pip3 install ipython flake8 jedi autopep8 ipdb redis requests
