---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: Install dev-related python packages to python2 installation
      shell: pip2 install ipython flake8 jedi autopep8 ipdb redis requests

    - name: Install dev-related python packages to python3 installation
      shell: pip3 install ipython flake8 jedi autopep8 ipdb redis requests

    - name: Configure git to use macOS keychain helper
      shell: git config --global credential.helper osxkeychain

    - shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

    - name: Show Library folder in Finder
      shell: chflags nohidden ~/Library

    - name: Show all filename extensions in Finder
      shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    - name: Save screenshots to Downloads folder
      shell: defaults write com.apple.screencapture location ~/Downloads/

    - name: Clone dotfiles
      git: repo=https://github.com/tomhogans/dotfiles.git dest=/Users/tomh/.dotfiles recursive=yes
