---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "gpg_private_key_file"
      prompt: "GPG private key"
      default: "/Volumes/USBKey/key.asc"

    - name: "credentials_file"
      prompt: "GPG-encrypted credentials archive"
      default: "/Volumes/USBKey/credentials.zip.gpg"

  vars_files:
    - vars/main.yml

  # roles:
    # - geerlingguy.homebrew

  tasks:
    - name: Import GPG private key
      shell: "gpg --import {{ gpg_private_key_file }}"
      ignore_errors: yes

    - name: Copy credentials archive to local filesystem
      copy:
        src: "{{ credentials_file }}"
        dest: "/tmp/credentials.zip.gpg"

    - name: Decrypt credentials archive
      shell: "gpg --decrypt /tmp/credentials.zip.gpg > /tmp/credentials.zip"

    - name: Extract credentials archive
      unarchive:
        src: "/tmp/credentials.zip"
        dest: "/tmp"

    - name: Install oh-my-zsh
      shell: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"

    - name: Copy dot files
      shell: echo "OK"

    - name: Configure git to use macOS keychain helper
      shell: git config --global credential.helper osxkeychain

    - name: Clone repo for Vundle (vim plugin manager)
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim recursive=yes

    - name: Install vim plugins via Vundle
      shell: vim +PluginInstall +qall

    - name: Install dev-related python packages to python2 installation
      shell: pip2 install ipython flake8 jedi autopep8 ipdb redis requests

    - name: Install dev-related python packages to python3 installation
      shell: pip3 install ipython flake8 jedi autopep8 ipdb redis requests

    - name: Show Library folder in Finder
      shell: chflags nohidden ~/Library

    - name: Show all filename extensions in Finder
      shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    - name: Save screenshots to Downloads folder
      shell: defaults write com.apple.screencapture location ~/Downloads/

