---
- name: Install oh-my-zsh
  shell: "curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh"

- template: src=eslintrc dest=~/.eslintrc

- shell: "mkdir -p ~/.config"
- template: src=flake8 dest=~/.config/flake8

- template: src=tmux.conf dest=~/.tmux.conf

- template: src=vimrc dest=~/.vimrc

- template: src=zshrc dest=~/.zshrc

- name: Clone repo for Vundle (vim plugin manager)
  git: repo=https://github.com/VundleVim/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim recursive=yes

- name: Install vim plugins via Vundle
  shell: vim +PluginInstall +qall

- git_config: 
    scope: global
    name: user.email
    value: "{{ git_email }}"

- git_config:
    scope: global
    name: core.editor
    value: vim

- git_config: 
    scope: global
    name: credential.helper
    value: osxkeychain

- git_config: 
    scope: global
    name: diff.tool
    value: vimdiff

- git_config: 
    scope: global
    name: merge.tool
    value: vimdiff

- git_config: 
    scope: global
    name: alias.st
    value: status

- git_config: 
    scope: global
    name: alias.co
    value: checkout

- git_config: 
    scope: global
    name: alias.br
    value: branch

- git_config: 
    scope: global
    name: alias.gr
    value: "grep -n --color --break --heading -B 2 -A 2 -p"
