- name: Import GPG private key
  shell: "gpg --import {{ gpg_private_key_file }}"
  ignore_errors: yes

- name: Copy credentials archive to local filesystem
  copy:
    src: "{{ credentials_file }}"
    dest: "/tmp/credentials.zip.gpg"

- name: Decrypt credentials archive
  shell: "gpg --decrypt /tmp/credentials.zip.gpg > /tmp/credentials.zip"

- name: Extract credentials archive
  unarchive:
    src: "/tmp/credentials.zip"
    dest: "/tmp"

- name: Import archived GPG private keys
  shell: "gpg --import /tmp/credentials/gpg/*"
  ignore_errors: yes

- name: Import SSH keys and configuration
  copy: src="/tmp/credentials/ssh/" dest="~/.ssh"

- name: Copy VPN configurations to ~/.vpnconfig
  copy: src="/tmp/credentials/vpn/" dest="~/.vpnconfig"

- name: Copy autoenv configurations to ~/.autoenv
  copy: src="/tmp/credentials/autoenv/" dest="~/.autoenv"

- name: Clean up credentials archive from tmp folder
  shell: "rm -rf /tmp/credentials"
