---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: "gpg_private_key_file"
      prompt: "GPG private key"
      default: "/Volumes/USBKey/key.asc"

    - name: "credentials_file"
      prompt: "GPG-encrypted credentials archive"
      default: "/Volumes/USBKey/credentials.zip.gpg"

  tasks:
    - name: Import GPG private key
      shell: "gpg --import {{ gpg_private_key_file }}"
      ignore_errors: yes

    - name: Copy credentials archive to local filesystem
      copy:
        src: "{{ credentials_file }}"
        dest: "/tmp/credentials.zip.gpg"

    - name: Decrypt credentials archive
      shell: "gpg --decrypt /tmp/credentials.zip.gpg > /tmp/credentials.zip"

    - name: Extract credentials archive
      unarchive:
        src: "/tmp/credentials.zip"
        dest: "/tmp"

    - name: Import archived GPG private keys
      shell: "gpg --import /tmp/credentials/gpg/*"
      ignore_errors: yes

    - name: Import SSH keys and configuration
      shell: "mv /tmp/credentials/ssh ~/.ssh"

    - name: Copy VPN configurations to ~/Downloads
      shell: "mv /tmp/credentials/vpn ~/.vpnconfig"

    - name: Copy autoenv configurations to ~/.autoenv
      shell: "mv /tmp/credentials/autoenv ~/.autoenv"

    - name: Clean up credentials archive from tmp folder
      shell: "rm -rf /tmp/credentials"
