# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"
CASE_SENSITIVE="true"

source $ZSH/oh-my-zsh.sh

unsetopt correct_all
unsetopt share_history

plugins=(brew mercurial git github gnu-utils osx python ssh-agent virtualenv)

# Put homebrew tools first on path
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.scripts

# Set commonly used variables
export LANG=en_US.UTF-8
export EDITOR=vim

#Java
export JAVA_HOME="$(/usr/libexec/java_home)"

# GOPATH
export GOPATH=/usr/local/gopath
export PATH=$PATH:/usr/local/gopath/bin

# Activate CLI helper tools
source /usr/local/opt/autoenv/activate.sh
eval $(thefuck --alias) 

# Download MP3 from YouTube
alias getmp3='python3 $(which youtube-dl) --extract-audio --audio-format mp3'

# Alias DNS flushing tools
alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder;'

# Functions to set JDK version
function removeFromPath() {
  export PATH=$(echo $PATH | sed -E -e "s;:$1;;" -e "s;$1:?;;")
}
function setjdk() {
  if [ $# -ne 0 ]; then
    removeFromPath '/System/Library/Frameworks/JavaVM.framework/Home/bin'
    if [ -n "${JAVA_HOME+x}" ]; then
      removeFromPath $JAVA_HOME
    fi
    export JAVA_HOME=`/usr/libexec/java_home -v $@`
    export PATH=$JAVA_HOME/bin:$PATH
  fi
  echo JAVA_HOME set to $JAVA_HOME
  java -version
}

